config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:new, :create] do
    post 'approve', on: :member
    post 'deny', on: :member
  end
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]


  root to: redirect('/cats')
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, :password_digest, :session_token, presence: true
  validates :username, :session_token, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token

  attr_reader :password

  has_many :cats,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: 'Cat'

  has_many :cat_rental_requests

  has_many :session_token_joins

  has_many :sessions,
  through: :session_token_joins,
  source: :session

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)

    if user
      return user if user.is_password?(password)
    end
    nil
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
    save
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end

  private

  def ensure_session_token
    # new_token = SessionToken.create(token: SecureRandom::urlsafe_base64, environment: )
    self.session_token ||= SecureRandom::urlsafe_base64
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_logged_out

  def new
    render :new
  end

  def create
    user = User.new(user_params)

    if user.save
      login_user!(user)
    else
      flash.now[:errors] = ["Username and/or password not valid"]
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<h1>Sign Up!</h1>

<% if flash.now[:errors] %>
  <% flash.now[:errors].each do |error| %>
    <p><%= error %></p>
  <% end %>
<% end %>

<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="username">Username: </label>
  <input type="text" name="user[username]" id="username">
  <br>

  <label for="password">Password: </label>
  <input type="password" name="user[password]" id="password">
  <br>

  <input type="submit" value="Sign Up!">
</form>